name: Accessibility Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  a11y-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: cd frontend && npm ci

    - name: Run accessibility tests
      run: cd frontend && npm run test:a11y

    - name: Build project
      run: cd frontend && npm run build

    - name: Start server for Lighthouse
      run: cd frontend && npm run preview & npx wait-on http://localhost:5173

    - name: Run Lighthouse CI
      run: cd frontend && npx lhci autorun
      env:
        LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

    - name: Archive accessibility results
      uses: actions/upload-artifact@v3
      with:
        name: accessibility-reports
        path: |
          frontend/lighthouse-report
          frontend/coverage-a11y
